import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./normalize.css";
import "./globals.css";
import React from "react";
import { Toaster } from "sonner";
import ThemeProvider from "@/components/app/providers/ThemeProvider";
import StoreProvider from "@/components/app/providers/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Lichi | Constructor",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): React.JSX.Element {
	return (
		<StoreProvider>
			<html lang="en">
				<Toaster />
				<body className={inter.className}>
					<ThemeProvider
						enableSystem
						disableTransitionOnChange
						attribute="class"
						defaultTheme="light"
					>
						{children}
					</ThemeProvider>
				</body>
			</html>
		</StoreProvider>
	);
}
